In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [2]:
text = [
"i am currently learning python programming",
"python programming is fun to learn",
"i am also learning java programming",
"i like java programming",

"i am learning data structures and algorithms",
"data structures are important for problem solving",
"algorithms help in writing efficient code",
"i practice coding every day to improve my skills",

"python is widely used in machine learning",
"machine learning is a part of artificial intelligence",
"artificial intelligence is shaping the future",
"i am interested in artificial intelligence and deep learning",

"deep learning uses neural networks",
"neural networks are inspired by the human brain",
"i want to build intelligent systems using ai",
"ai applications are growing rapidly",

"i also enjoy solving coding problems",
"coding platforms help improve logical thinking",
"i use online judges to practice problems",
"consistent practice leads to better performance",

"java is an object oriented programming language",
"object oriented programming focuses on classes and objects",
"i understand concepts like inheritance and polymorphism",
"java is widely used in enterprise applications",

"python has simple syntax and is easy to learn",
"many beginners start with python programming",
"python supports multiple programming paradigms",
"i enjoy writing python scripts",

"i am learning web development basics",
"html and css are used for designing web pages",
"javascript makes web pages interactive",
"frontend development is creative and interesting",

"backend development handles server side logic",
"databases are used to store application data",
"sql is used to query databases",
"i am learning how to connect backend with frontend",

"i want to become a software engineer",
"software engineering requires problem solving skills",
"good developers write clean and efficient code",
"teamwork is important in software development",

"i am exploring android development",
"android apps are built using java or kotlin",
"mobile development is a valuable skill",
"i want to create useful mobile applications",

"i am interested in augmented reality and virtual reality",
"ar and vr provide immersive experiences",
"unity is used for building ar applications",
"i want to develop innovative ar projects",

"i am working on improving my coding speed",
"practice helps in competitive programming",
"competitive programming improves logical thinking",
"i participate in coding contests regularly",

"i learn new technologies every day",
"technology is evolving very fast",
"continuous learning is important in tech field",
"i enjoy learning new programming languages",

"i am building projects to gain experience",
"projects help in understanding real world problems",
"practical knowledge is as important as theory",
"i try to implement what i learn",

"i am learning about data science",
"data science involves data analysis and visualization",
"python libraries like pandas and numpy are useful",
"data visualization helps in understanding patterns",

"i want to master machine learning concepts",
"supervised learning uses labeled data",
"unsupervised learning finds hidden patterns",
"models improve with more data and training",

"i am learning about neural networks",
"training neural networks requires data and computation",
"loss functions measure model performance",
"optimization algorithms update model weights",

"i am also studying operating systems",
"operating systems manage hardware and software resources",
"process scheduling is an important concept",
"memory management improves system efficiency",

"computer networks are also important",
"networks enable communication between devices",
"protocols define rules for communication",
"i am learning about tcp and ip",

"i want to build scalable applications",
"scalability is important for large systems",
"cloud computing helps in scaling applications",
"many companies use cloud platforms",

"i am learning version control systems",
"git is widely used for version control",
"github helps in collaboration",
"i push my code regularly to repositories",

"debugging is an important skill",
"finding and fixing errors improves code quality",
"i try to understand bugs carefully",
"patience is required for debugging",

"i enjoy working on challenging problems",
"problem solving improves analytical thinking",
"i break problems into smaller parts",
"this approach makes solving easier",

"i am preparing for technical interviews",
"interviews test problem solving and coding skills",
"data structures questions are commonly asked",
"practice is key to success in interviews",

"i am building strong fundamentals",
"fundamentals are important for advanced topics",
"i revise concepts regularly",
"consistency is important for learning",

"i want to contribute to open source",
"open source helps in learning from others",
"collaboration improves coding skills",
"i explore open source projects online",

"i enjoy learning new concepts",
"learning keeps me motivated",
"technology offers many opportunities",
"i want to grow in my career",

"i am improving my logical thinking",
"logic building is important for programming",
"practice makes logic stronger",
"i solve puzzles and coding problems",

"i want to become a better programmer",
"good programmers write efficient code",
"understanding concepts is more important than memorizing",
"i focus on clarity and practice"
]

In [3]:
tokenizer =Tokenizer()
tokenizer.fit_on_texts(text)

In [4]:
sequences = tokenizer.texts_to_sequences(text)
print(sequences)

[[1, 6, 118, 4, 14, 8], [14, 8, 2, 119, 3, 31], [1, 6, 32, 4, 23, 8], [1, 42, 23, 8], [1, 6, 4, 10, 43, 5, 44], [10, 43, 12, 9, 11, 33, 18], [44, 45, 7, 67, 46, 24], [1, 16, 15, 68, 69, 3, 47, 25, 34], [14, 2, 48, 17, 7, 49, 4], [49, 4, 2, 35, 120, 121, 50, 51], [50, 51, 2, 122, 70, 123], [1, 6, 71, 7, 50, 51, 5, 72, 4], [72, 4, 73, 36, 19], [36, 19, 12, 124, 125, 70, 126, 127], [1, 13, 3, 74, 128, 26, 75, 76], [76, 20, 12, 129, 130], [1, 32, 27, 18, 15, 21], [15, 77, 45, 47, 52, 37], [1, 78, 79, 131, 3, 16, 21], [132, 16, 133, 3, 80, 81], [23, 2, 53, 82, 83, 8, 134], [82, 83, 8, 135, 38, 136, 5, 137], [1, 84, 28, 42, 138, 5, 139], [23, 2, 48, 17, 7, 140, 20], [14, 141, 142, 143, 5, 2, 144, 3, 31], [54, 145, 146, 55, 14, 8], [14, 147, 148, 8, 149], [1, 27, 67, 14, 150], [1, 6, 4, 56, 22, 151], [152, 5, 153, 12, 17, 11, 154, 56, 85], [155, 57, 56, 85, 156], [86, 22, 2, 157, 5, 158], [87, 22, 159, 160, 161, 58], [88, 12, 17, 3, 162, 163, 10], [164, 2, 17, 3, 165, 88], [1, 6, 4, 166, 3, 1

In [5]:
X = []
y =[]
for seq in sequences:
    for i in range(1, len(seq)):
        X.append(seq[:i])
        y.append(seq[i])

In [6]:
X

[[1],
 [1, 6],
 [1, 6, 118],
 [1, 6, 118, 4],
 [1, 6, 118, 4, 14],
 [14],
 [14, 8],
 [14, 8, 2],
 [14, 8, 2, 119],
 [14, 8, 2, 119, 3],
 [1],
 [1, 6],
 [1, 6, 32],
 [1, 6, 32, 4],
 [1, 6, 32, 4, 23],
 [1],
 [1, 42],
 [1, 42, 23],
 [1],
 [1, 6],
 [1, 6, 4],
 [1, 6, 4, 10],
 [1, 6, 4, 10, 43],
 [1, 6, 4, 10, 43, 5],
 [10],
 [10, 43],
 [10, 43, 12],
 [10, 43, 12, 9],
 [10, 43, 12, 9, 11],
 [10, 43, 12, 9, 11, 33],
 [44],
 [44, 45],
 [44, 45, 7],
 [44, 45, 7, 67],
 [44, 45, 7, 67, 46],
 [1],
 [1, 16],
 [1, 16, 15],
 [1, 16, 15, 68],
 [1, 16, 15, 68, 69],
 [1, 16, 15, 68, 69, 3],
 [1, 16, 15, 68, 69, 3, 47],
 [1, 16, 15, 68, 69, 3, 47, 25],
 [14],
 [14, 2],
 [14, 2, 48],
 [14, 2, 48, 17],
 [14, 2, 48, 17, 7],
 [14, 2, 48, 17, 7, 49],
 [49],
 [49, 4],
 [49, 4, 2],
 [49, 4, 2, 35],
 [49, 4, 2, 35, 120],
 [49, 4, 2, 35, 120, 121],
 [49, 4, 2, 35, 120, 121, 50],
 [50],
 [50, 51],
 [50, 51, 2],
 [50, 51, 2, 122],
 [50, 51, 2, 122, 70],
 [1],
 [1, 6],
 [1, 6, 71],
 [1, 6, 71, 7],
 [1, 6, 71, 7, 5

In [7]:
X = pad_sequences(X)

In [8]:
X

array([[  0,   0,   0, ...,   0,   0,   1],
       [  0,   0,   0, ...,   0,   1,   6],
       [  0,   0,   0, ...,   1,   6, 118],
       ...,
       [  0,   0,   0, ...,   1, 306,  38],
       [  0,   0,   0, ..., 306,  38, 307],
       [  0,   0,   0, ...,  38, 307,   5]], shape=(626, 8), dtype=int32)

In [9]:
y = np.array(y)

In [10]:
y

array([  6, 118,   4,  14,   8,   8,   2, 119,   3,  31,   6,  32,   4,
        23,   8,  42,  23,   8,   6,   4,  10,  43,   5,  44,  43,  12,
         9,  11,  33,  18,  45,   7,  67,  46,  24,  16,  15,  68,  69,
         3,  47,  25,  34,   2,  48,  17,   7,  49,   4,   4,   2,  35,
       120, 121,  50,  51,  51,   2, 122,  70, 123,   6,  71,   7,  50,
        51,   5,  72,   4,   4,  73,  36,  19,  19,  12, 124, 125,  70,
       126, 127,  13,   3,  74, 128,  26,  75,  76,  20,  12, 129, 130,
        32,  27,  18,  15,  21,  77,  45,  47,  52,  37,  78,  79, 131,
         3,  16,  21,  16, 133,   3,  80,  81,   2,  53,  82,  83,   8,
       134,  83,   8, 135,  38, 136,   5, 137,  84,  28,  42, 138,   5,
       139,   2,  48,  17,   7, 140,  20, 141, 142, 143,   5,   2, 144,
         3,  31, 145, 146,  55,  14,   8, 147, 148,   8, 149,  27,  67,
        14, 150,   6,   4,  56,  22, 151,   5, 153,  12,  17,  11, 154,
        56,  85,  57,  56,  85, 156,  22,   2, 157,   5, 158,  2

In [11]:
vocab_size = len(tokenizer.word_index) + 1

In [12]:
model = Sequential([
    Embedding(vocab_size, 15, input_length = X.shape[1]),
    SimpleRNN(32),
    Dense(vocab_size, activation='softmax')
])

C:\Program Files\Python313\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.compile(
    optimizer='adam',
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
)

In [20]:
model.fit(X,y,
         epochs=1000)

Epoch 1/1000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.2862 
Epoch 2/1000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.2685 
Epoch 3/1000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.2473 
Epoch 4/1000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.2263 
Epoch 5/1000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.2093 
Epoch 6/1000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.1894
Epoch 7/1000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.1728 
Epoch 8/1000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.1553 
Epoch 9/1000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.1401 
Epoch 10/1000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.1224 
Epoch 11/1000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.1052 
Epoch 12/1000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0924 
Epoch 13/1000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0740 
Epoch 14/1000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0594 
Epoch 15/1000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 

In [21]:
input_text = "i want"
seq = tokenizer.texts_to_sequences([input_text])[0]
seq = pad_sequences([seq], maxlen =X.shape[1])
pred = model.predict(seq)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step


In [22]:
pred

array([[1.77743410e-11, 2.50580394e-12, 2.06516138e-08, 9.99958277e-01,
        3.16425321e-05, 1.25702385e-07, 8.67641792e-11, 9.75993686e-08,
        1.59156662e-06, 8.06754130e-08, 7.91253285e-10, 6.44091314e-09,
        1.33504284e-06, 8.80490333e-11, 2.82100482e-10, 2.99035690e-07,
        1.98233230e-09, 1.30838682e-08, 1.53583812e-10, 5.03733828e-13,
        1.07878984e-12, 4.89530583e-10, 8.69934680e-12, 1.05715017e-07,
        2.02018610e-12, 1.78990399e-06, 3.33886586e-12, 7.86455523e-09,
        5.54492146e-07, 2.19384866e-09, 7.57380595e-13, 1.74896000e-11,
        5.70953944e-07, 4.84731422e-11, 1.41089321e-12, 4.04431995e-13,
        2.79466117e-10, 1.69238660e-13, 3.80545595e-11, 2.79185617e-08,
        7.94215804e-09, 9.34581371e-11, 2.24341899e-11, 1.85075633e-09,
        8.41622813e-11, 1.84979609e-13, 3.23666419e-12, 1.27803471e-11,
        1.01305433e-12, 7.44134355e-12, 1.54919877e-09, 5.76207380e-11,
        3.91228553e-13, 4.62940866e-11, 2.44485560e-11, 3.818792

In [23]:
predicted_index=np.argmax(pred)
for word, index in tokenizer.word_index.items():
    if index == predicted_index:
        print("Next word:", word)

Next word: to


In [24]:
def predict_next_word(model,tokenizer,input_text,n_words):
  seq = tokenizer.texts_to_sequences([input_text])[0]
  seq = pad_sequences([seq],maxlen=X.shape[1])
  pred=model.predict(seq)
  predicted_index = np.argmax(pred)
  for word,index in tokenizer.word_index.items():
    if index == predicted_index:
      return word

In [25]:
text = "i want"
for _ in range(5):
  next_word = predict_next_word(model,tokenizer,text,X.shape[1])
  text +=" "+next_word

print(text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
i want to become a better programmer
